dist: trusty

language: node_js

node_js:
  - "0.12"
  - "4.0"
  - "4"
  - "5"
  - "stable"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

sudo: required

services:
  - mysql

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install mysql
  - mysql -u root -e 'create database myapp_dev;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('grut') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - export NODE_ENV=development

script:
  - npm run lint
  - npm test
  - npm run test-node

env:
  - TRAVIS=travis CXX=g++-4.8
